config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :animal_kinds, except: :show
  resources :animals
end

app/models/animal.rb
class Animal < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :image, ImageUploader

  belongs_to :animal_kind

  validates :name, :image, :date_of_birth, presence: true
  validates :adoption_status, inclusion: [true, false]
  validate :verify_adoption_status

  scope :animal_sort, -> (sort_params) {
    if sort_params == 'waiting'
      where(adoption_status: false)
    elsif sort_params == 'adopted'
      where(adoption_status: true)
    end
  }

  def date_of_birth_br
    self.date_of_birth.to_s.split('-').reverse().join('/')
  end

  private

  def verify_adoption_status
    errors.add(:adopter_name, 'não pode ficar em branco') if adoption_status == true && adopter_name.blank?
  end
end

app/models/animal_kind.rb
class AnimalKind < ApplicationRecord
  extend FriendlyId
  friendly_id :kind, use: :slugged

  has_many :animals

  validates :kind, presence: true, uniqueness: { case_sensitive: false }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animal_kinds_controller.rb
class AnimalKindsController < ApplicationController
  before_action :set_animal_kind, only: [:edit, :update, :destroy, :status]

  def index
    @animal_kinds = AnimalKind.order(id: :desc)
  end

  def new
    @animal_kind = AnimalKind.new
  end

  def create
    @animal_kind = AnimalKind.new(animal_kind_params)

    if @animal_kind.save
      flash[:success] = 'Tipo de animal cadastrado com sucesso.'
      redirect_to animal_kinds_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @animal_kind.update(animal_kind_params)
      flash[:success] = 'Tipo de animal atualizado com sucesso.'
      redirect_to animal_kinds_path
    else
      render :edit
    end
  end

  def destroy
    animal_count = Animal.where(animal_kind: @animal_kind).count

    if animal_count > 0
      flash[:error] = 'Esse tipo de animal não pode ser excluído pois há dados relacionados a ele.'
      return redirect_to animal_kinds_path
    end

    if @animal_kind.destroy
      flash[:success] = 'Tipo de animal excluído com sucesso.'
      redirect_to animal_kinds_path
    else
      render :index
    end
  end

  private

  def animal_kind_params
    params.require(:animal_kind).permit(:kind)
  end

  def set_animal_kind
    @animal_kind = AnimalKind.friendly.find(params[:id])
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy, :status]
  before_action :set_animal_kinds, only: [:new, :create, :edit, :update]

  def index
    @animals = Animal.animal_sort(sort_params).order(id: :desc)
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)

    if @animal.save
      flash[:success] = 'Animal cadastrado com sucesso.'
      redirect_to animals_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @animal.update(animal_params)
      flash[:success] = 'Animal atualizado com sucesso.'
      redirect_to animals_path
    else
      render :edit
    end
  end

  def destroy
    if @animal.destroy
      flash[:success] = 'Animal excluído com sucesso.'
      redirect_to animals_path
    else
      render :index
    end
  end

  private

  def set_animal_kinds
    @animal_kinds = AnimalKind.select('id, kind').collect { |a| [ a.kind, a.id ] }
  end

  def animal_params
    params.require(:animal).permit(
      :name,
      :image,
      :image_cache,
      :date_of_birth,
      :adoption_status,
      :adopter_name,
      :animal_kind_id
    )
  end

  def set_animal
    @animal = Animal.friendly.find(params[:id])
  end

  def sort_params
    params[:sort].blank? ? nil : params[:sort].to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message_class(level)
    case level.to_s
    when 'notice'
      'alert-success'
    when 'success'
      'alert-success'
    when 'info'
      'alert-info'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-danger'
    when 'danger'
      'alert-danger'
    end
  end

  def get_age(birth)
    today = Date.current

    res = today.year - birth.year

    if res == 0
      'Menos de um ano'
    elsif res == 1
      '1 ano'
    else
      "#{res} anos"
    end
  end
end

app/views/animal_kinds/_form.html.erb
<% provide :page_title, "#{page} Tipo de Animal" %>

<div class="container">
  <div class="page_header pt-5 pb-5 border-bottom">
    <div class="row text-center">
      <div class="col-md-4 text-md-left">
        <h1 class="h2 mb-0"><%= page %> Tipo de Animal</h1>
      </div>

      <div class="col-md-8 text-md-right mt-3 mt-md-0">
        <%= link_to 'Voltar', animal_kinds_path, class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  </div>

  <div class="page_content pt-5 pb-5">
    <% if @animal_kind.errors.any? %>
    <div class="alert alert-danger">
      <h3 class="title h4 font-weight-bold">
        <%= pluralize(@animal_kind.errors.count, 'erro', 'erros') %>
        <%= @animal_kind.errors.count > 1 ? 'proibiram' : 'proibiu' %> este tipo de animal de ser salvo:
      </h3>

      <ul class="mb-0">
        <% @animal_kind.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="card">
      <div class="card-body">
        <%= form_with model: [@animal_kind], local: true do |f| %>
          <div class="mb-3">
            <%= f.label :kind, class: 'form-label' %> <small class="text-danger">*</small>
            <%= f.text_field :kind, autofocus: true, autocomplete: 'kind', class: 'form-control' %>
          </div>

          <%= f.submit nil, class: 'btn btn-primary' %>
          <%= link_to 'Cancelar', animal_kinds_path, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animal_kinds/index.html.erb
<% provide :page_title, 'Tipos de Animais' %>

<div class="container">
  <div class="pt-5 pb-5 border-bottom">
    <div class="row text-center">
      <div class="col-md-3 text-md-left">
        <h1 class="h2 mb-0">Tipos de Animais</h1>
      </div>
      <div class="col-md-9 text-md-right mt-3 mt-md-0">
        <%= link_to 'Novo', new_animal_kind_path, class: 'btn btn-outline-primary' %>
      </div>
    </div>
  </div>

  <div class="pt-5 pb-5">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered mb-0">
            <thead>
              <tr>
                <th>Tipo</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @animal_kinds.each do |animal_kind| %>
              <tr>
                <td><%= animal_kind.kind %></td>
                <td>
                  <div class="btn-group" role="group">
                    <%= link_to 'Editar', edit_animal_kind_path(animal_kind), class: 'btn btn-warning' %>
                    <%= link_to 'Excluir', animal_kind_path(animal_kind), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger' %>
                  </div>
                </td>
              </tr>
              <% end %>

              <% if @animal_kinds.length == 0 %>
              <tr>
                <td colspan="2">Nenhum tipo de animal encontrado</td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animals/_form.html.erb
<% provide :page_title, "#{page} Animal" %>

<div class="container">
  <div class="page_header pt-5 pb-5 border-bottom">
    <div class="row text-center">
      <div class="col-md-4 text-md-left">
        <h1 class="h2 mb-0"><%= page %> Animal</h1>
      </div>

      <div class="col-md-8 text-md-right mt-3 mt-md-0">
        <%= link_to 'Voltar', animals_path, class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  </div>

  <div class="page_content pt-5 pb-5">
    <% if @animal.errors.any? %>
    <div class="alert alert-danger">
      <h3 class="title h4 font-weight-bold">
        <%= pluralize(@animal.errors.count, 'erro', 'erros') %>
        <%= @animal.errors.count > 1 ? 'proibiram' : 'proibiu' %> este animal de ser salvo:
      </h3>

      <ul class="mb-0">
        <% @animal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="card">
      <div class="card-body">
        <%= form_with model: [@animal], local: true do |f| %>
          <div class="mb-3">
            <%= f.label :animal_kind_id, class: 'form-label' %> <small class="text-danger">*</small>
            <%= f.select(:animal_kind_id, @animal_kinds, { include_blank: 'Escolher' }, class: 'form-select') %>
          </div>

          <div class="mb-3">
            <%= f.label :name, class: 'form-label' %> <small class="text-danger">*</small>
            <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label :image, class: 'form-label' %>
            <% if @animal.new_record? %> <small class="text-danger">*</small> <% end %>
            <%= f.file_field :image, class: 'd-block' %>
            <%= f.hidden_field :image_cache %>
          </div>

          <div class="mb-3">
            <%= f.label :date_of_birth, class: 'form-label' %> <small class="text-danger">*</small>
            <% if @animal.new_record? %>
            <%= f.text_field :date_of_birth, autocomplete: 'date_of_birth', class: 'form-control' %>
            <% else %>
              <%= f.text_field :date_of_birth, autocomplete: 'date_of_birth', class: 'form-control', value: @animal.date_of_birth_br %>
            <% end %>
          </div>

          <div class="mb-3">
            <%= f.label :adoption_status, class: 'form-label' %>
            <%= f.select(:adoption_status, [['Aguardando', false], ['Adotado', true]], {}, class: 'form-select') %>
          </div>

          <% if @animal.adoption_status == true %>
          <div class="mb-3 show_animal_adopter_name_wrap" id="animal_adopter_name_wrap">
          <% else %>
          <div class="mb-3" id="animal_adopter_name_wrap">
          <% end %>
            <%= f.label :adopter_name, class: 'form-label' %> <small class="text-danger">*</small>
            <%= f.text_field :adopter_name, autocomplete: 'adopter_name', class: 'form-control' %>
          </div>

          <%= f.submit nil, class: 'btn btn-primary' %>
          <%= link_to 'Cancelar', animals_path, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animals/_sort.html.erb
<div class="row justify-content-end mt-5">
    <div class="col-md-3">
      <%= form_with url: animals_path, method: :get, local: true, id: 'animal_sort_form' do %>
        <%= select_tag(:sort,
          options_for_select([
            ['Todos', 'all'],
            ['Aguardando Adoção', 'waiting'],
            ['Adotados', 'adopted']
          ], params[:sort]), { id: 'animal_sort', class: 'form-select' }) %>
      <% end %>
    </div>
  </div>

app/views/animals/edit.html.erb
<%= render 'form', page: 'Editar' %>

app/views/animals/index.html.erb
<% provide :page_title, 'Animais' %>

<div class="container">
  <div class="pt-5 pb-5 border-bottom">
    <div class="row text-center">
      <div class="col-md-3 text-md-left">
        <h1 class="h2 mb-0">Animais</h1>
      </div>
      <div class="col-md-9 text-md-right mt-3 mt-md-0">
        <%= link_to 'Novo', new_animal_path, class: 'btn btn-outline-primary' %>
      </div>
    </div>
  </div>

  <%= render 'sort' %>

  <div class="pt-5 pb-5">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered mb-0">
            <thead>
              <tr>
                <th>Foto</th>
                <th>Nome</th>
                <th>Status de Adoção</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @animals.each do |animal| %>
              <tr>
                <td><%= image_tag(animal.image_url('medium'), class: 'animal_photo_list', id: "animal_photo_list_#{animal.id}") if animal.image.present? %></td>
                <td><%= animal.name %></td>
                <td>
                <% if animal.adoption_status == true %>
                  Adotado
                <% else %>
                  Aguardando
                <% end %>
                </td>
                <td>
                  <div class="btn-group" role="group">
                    <%= link_to 'Visualizar', animal_path(animal), class: 'btn btn-info' %>
                    <%= link_to 'Editar', edit_animal_path(animal), class: 'btn btn-warning' %>
                    <%= link_to 'Excluir', animal_path(animal), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger' %>
                  </div>
                </td>
              </tr>
              <% end %>

              <% if @animals.length == 0 %>
              <tr>
                <td colspan="4">Nenhum animal encontrado</td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animals/new.html.erb
<%= render 'form', page: 'Novo' %>

app/views/animals/show.html.erb
<% provide :page_title, 'Animais' %>

<div class="container">
  <div class="pt-5 pb-5 border-bottom">
    <div class="row text-center">
      <div class="col-md-3 text-md-left">
        <h1 class="h2 mb-0">Animal</h1>
      </div>
      <div class="col-md-9 text-md-right mt-3 mt-md-0">
        <%= link_to 'Voltar', animals_path, class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  </div>

  <div class="pt-5 pb-5">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <div class="card-body">
                <%= image_tag(@animal.image_url, class: 'img-fluid', id: 'animal_photo') if @animal.image.present? %>
              </div>
            </div>
          </div>

          <div class="col-md-6">
            <div class="table-responsive">
              <table class="table table-bordered">
                <tbody>
                  <tr>
                    <td class="font-weight-bold">Tipo de animal</td>
                    <td><%= @animal.animal_kind.kind %></td>
                  </tr>
                  <tr>
                    <td class="font-weight-bold">Nome</td>
                    <td><%= @animal.name %></td>
                  </tr>
                  <tr>
                    <td class="font-weight-bold">Nascimento</td>
                    <td><%= l @animal.date_of_birth, format: :long %></td>
                  </tr>
                  <tr>
                    <td class="font-weight-bold">Idade</td>
                    <td><%= get_age(@animal.date_of_birth) %></td>
                  </tr>
                  <tr>
                    <td class="font-weight-bold">Status</td>
                    <td>
                      <% if @animal.adoption_status === true %>
                        Adotado por <%= @animal.adopter_name %>
                      <% else %>
                        Aguardando adoção
                      <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% provide :page_title, 'Home' %>

<div class="container">
  <div class="pt-5 pb-5 text-center">
    <h1 class="h1 mb-0">Seja bem-vindo ao Lifepet</h1>
    <h2 class="h4 mt-2 mb-0 text-secondary">Encontre o bichinho que deixará você ainda mais feliz</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :page_title %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/flash' %>
    <%= render partial: 'layouts/shared/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render partial: 'layouts/shared/footer' %>

    <script data-turbolinks-eval="false" src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <script data-turbolinks-eval="false" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script data-turbolinks-eval="false" src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-masker/1.2.0/vanilla-masker.min.js"></script>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer>
  <div class="container">
    <p class="text-white text-center pt-5 pb-4">&copy; <%= Date.current.year %> Lifepet - Todos os direitos reservados</p>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Lifepet', root_path, alt: 'lifepet', class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, alt: 'home', class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Animais
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Tipos', animal_kinds_path, alt: 'tipos', class: 'dropdown-item' %></li>
            <li><%= link_to 'Listar', animals_path, alt: 'listar animais', class: 'dropdown-item' %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert <%= flash_message_class(key) %> alert-dismissible fade show alert_top" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>